# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: mas-cli
summary: MAS CLI Tool
description: MAS CLI is a command-line tool for managing MAS policies.
version: 0.17.1
base: core22
license: Apache-2.0
confinement: strict
architectures:
  - build-on: [amd64]
    build-for: [amd64]

parts:
  mas-cli:
    plugin: rust
    rust-channel: stable
    rust-cargo-parameters:
      - "--features dist"
      - "--no-default-features"
    source: https://github.com/element-hq/matrix-authentication-service
    source-type: git
    source-tag: v0.17.1
    build-snaps:
      - go/1.22/stable
    override-build: |
      # Build the open-policy-agent binary
      git clone --depth 1 --branch v0.70.0 https://github.com/open-policy-agent/opa.git
      (cd opa; make build; chmod +x opa_linux_amd64; mv opa_linux_amd64 /usr/local/bin/opa)
      # Build MAS policies
      (cd policies; make)
      # Install policy file
      mkdir -p $CRAFT_PART_INSTALL/mas/share
      cp policies/policy.wasm $CRAFT_PART_INSTALL/mas/share/policy.wasm
      craftctl default
    override-prime: |
        craftctl default
        cp $SNAPCRAFT_PART_BUILD/target/release/mas-cli $SNAPCRAFT_PRIME/

apps:
  mas-cli:
    command: mas-cli
